# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
#networks:
 # rabbitmq-prometheus:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:

services:
  creditcard:
    container_name: csca5028-creditcardprocessor
    image: nikhilrajwade/csca5028.final.credit-card-processor:latest
    build:
        context: .  
        dockerfile: credit-card-processor/Dockerfile.local
    ports:
      - '9001:80'
    hostname: card0
  pos:
    container_name: csca5028-pos
    image: nikhilrajwade/csca5028.final.point-of-sale-app:latest
    build:
        context: .  
        dockerfile: point-of-sale-app/Dockerfile.local
    ports:
        - '9002:80'
    restart: always
  salescollector:
    container_name: csca5028-salescollector
    image: nikhilrajwade/csca5028.final.sales-collector:latest
    build:
        context: .  
        dockerfile: sales-collector/Dockerfile.local
    ports:
    - '9003:80'
    restart: always
  blazorwebapp:
    container_name: csca5028-saleswebapp
    image: nikhilrajwade/csca5028.final.csca5028.blazor.webapp:latest
    build:
        context: .  
        dockerfile: csca5028.blazor.webapp/Dockerfile.local
    ports:
    - '80:80'
    - '443:443'
    restart: always
  
    #networks:
     # - "rabbitmq-prometheus"   