# This is a comment. You can use # to write comments in a .http file.
# You can use @ to define variables that can be reused in the file.
@url = http://host.docker.internal:15672/api/queues/%2f/houston-pos/get

# This is the request line. You need to specify the method, the URL, and the HTTP version.
POST {{url}} HTTP/1.1

# These are the request headers. You need to specify the content type, the authorization, and any other headers you want.
Content-Type: application/json
Authorization: Basic guest:guest |> base64

# This is an empty line that separates the request headers and the request body.


# This is the request body. You need to specify the parameters for the request in JSON format.
{
  "count": 1,
  "requeue": false,
  "encoding": "auto",
  "truncate": 50000,
  "ackmode": "ack_requeue_false"
}
