name: Delete workflow runs
on:
  workflow_dispatch:
  uses: dmvict/clean-workflow-runs@v1.0.0
  with:
    token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
    repo: user/repo
    workflow_id: TheWorkflow.yml
    branch: main
    run_conclusions: |
      failure
      timed_out
    save_period: 30
    save_min_runs_number: 1
    dry: true
