name: Delete workflow runs
on:
  workflow_dispatch:

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.2.1
        with:
            token: ${{ secrets.GIT_PAT }}
            repo: nick-rajwade/csca5028.final
            #workflow_id: TheWorkflow.yml
            branch: main
            run_conclusions: failure, success
            save_period: 5
            save_min_runs_number: 0
            dry: false
