name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  push_to_registry:
    name: Push Docker image(s) to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [credit-card-processor, point-of-sale-app, sales-collector, sales-web-app]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set version
      run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build and publish the Docker image(s)
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{matrix.project}}
        file: ${{matrix.project}}/Dockerfile
        push: true
        tags: nikhilrajwade/csca5028.final.${{matrix.project}}:${{env.VERSION}}
