name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [credit-card-processor, point-of-sale-app, sales-collector, sales-web-app]

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish the Docker image(s)
      uses: docker/build-push-action@v2
      with:
        context: ${{matrix.project}}
        file: ${{matrix.project}}/Dockerfile
        push: true
        tags: user/repo:${{matrix.project}}
