name: Build and Publish NuGet package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./csca5028.lib/
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./csca5028.lib/
      - name: Publish
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ./csca5028.lib/csca5028.lib.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_REGEX: ^\s*<AssemblyVersion>(.*)<\/AssemblyVersion>\s*$
