name: build.publish.nuget

on:
  push:
    branches: [ master ]
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install gitversion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          #updateAssemblyInfo: true
          useConfigFile: true
          configFilePath: /home/runner/work/csca5028.final/csca5028.final/GitVersion.yml
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./csca5028.lib/
      - name: Build
        run: dotnet build --no-restore --configuration Release && dotnet pack --no-restore --no-build --configuration Release --output ./nuget -p:Version=$GITVERSION_FULLSEMVER
        working-directory: ./csca5028.lib/
      #- name: Add GitHub Packages as Source
        #run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      #- name: Add nuget.org as Source
      #  run: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
      - name: Publish to nuget.org
        run: dotnet nuget push ./nuget/*.nupkg --source nuget.org --api-key ${{ secrets.NUGET_API_KEY }}
        working-directory: ./csca5028.lib/
        #- name: Publish to GitHub Packages
      #  run: dotnet nuget push ./nuget/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}
      #  working-directory: ./csca5028.lib/
      #  env:
      #      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
       # - name: Publish
        #uses: tedd/publish-nuget-neo@v1
        #with:
         # PROJECT_FILE_PATH: ./csca5028.lib/csca5028.lib.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          #VERSION_STATIC: ${{env.GitVersion_SemVer}}


